- name: install apache2
  package:
    name: "{{package}}"
    state: latest
- name: copy index.html file
  copy:
    src: b4-ansible\roles\httpdrole\files\index.html
    dest: /var/www/html/index.html
    notify:
      - restart service
  