- name: install apache2
  package:
    name: "{{package}}"
    state: latest
- name: copy index.html file
  copy:
    src: ./index.html
    dest: /var/www/html/index.html
- name: restart httpd
  systemd:
     name: "{{package}}"
     state: restarted
     enable: true
  