- name: install apache2
  package:
    name: httpd
    state: latest
- name: copy index.html file
  copy:
    src: /home/ubuntu/b4-ansible/index.html
    dest: /var/www/html/index.html
- name: restart httpd
  systemd:
     name: httpd
     state: restarted
     enable: true
  