- name: copy file from ansible server to ansible host
  hosts: all
  tasks:
    - name: copy file
      copy:
        src: /home/ubuntu/b4-ansible/index.html
        dest: /var/www/html/index.html
    - name: restart apache2
      systemd:
