- name: copy file from ansible server to ansible host
  hosts: all
  tasks:
    - name: copy file
      copy:
        src: ./bindex.html
        dest: /var/www/html/index.html
    - name: restart apache2
      systemd:
        name: apache2
        state: restarted

