- name: change line in the existing file
  hosts: all
  tasks:
    - name: changing line
      lineinfile:
        path: /var/www/html/index.html
        regexp: '^h1'
        line: <h1> Hello this is lineinfile module<h1
