- name: change line in the existing file
  hosts: all
  tasks:
    # - name: changing line
    #   lineinfile:
    #     path: /var/www/html/index.html
    #     regexp: '^h1'
    #     line: <h1> Hello this is lineinfile module</h1>
    - name: block adding
      blockinfile:
        path: /var/www/html/index.html
        block: |
          <H1>this is new block added
          <h2line1
          line2   
    - name: restart apache2
      systemd:
        name: apache2
        state: restarted        