- name: change line in the existing file
  hosts: all
  tasks:
    # - name: changing line
    #   lineinfile:
    #     path: /var/www/html/index.html
    #     regexp: '^h1'
    #     line: <h1> Hello this is lineinfile module</h1>
    - name: block adding
      blockinfile:
        path: /var/www/html/index.html
        regexp: '^h1'
        block: |
           this is new block added
           line1
            line2           