- name: install multiple software
  hosts: all
  tasks:
    - name: print diff msg
      debug: 
        msg: {{item}}
    - name: install diff package
      package: 
         name: "{{item}}"
         state: latest 
      loop:
        - vim
        - wget
        - nginx