- name: this is my 1st playbook
  hosts: all
  vars:
    pokemon: "pikachu"
  tasks:
    - name: your fevourite pokemon
      debug:
        msg: "{{pokemon}}"
    - name: print HI
      debug:
        msg: "{{pokemon}}"
    - name: print HI
      debug:
        msg: "{{pokemon}}"
      vars:
        pokemon: "pichu"
