- name: this is my 1st playbook
  hosts: all
  vars:                 #global variable
    pokemon: "pikachu"
  # vars_files:         #file varible
  #    - ./var.txt
  # vars_prompt:
  #       name: pokemon
  #       prompt: "what is your name:"
  #       private: false
  tasks:
    - name: your fevourite pokemon
      debug:
        msg: "{{pokemon}}"    #variable calling
    - name: print HI
      debug:
        msg: "{{pokemon}}"
    - name: local varible available
      debug:
        msg: "{{pokemon}}"
      vars:                     #local variable
        pokemon: "pichu"
    - name: registor output as variable
      shell: hostname
      register: host
    - name: print the register value
      debug:
        msg: "{{host.stdout}}"
    
- name: this is a play at the top level of a file
  hosts: all
  tasks:
  - name: say hi
    debug:
      msg: "hi..."
    tags:
      - task1
  - name: say "hello..."
    debug:
      msg: "hello..."
    tags:
      - task2

